# SITE CONFIGURATION
baseurl: ""
url: "https://strymon-system.github.io/"
future: false

# DOCUMENTATION
collections:
  docs:
    output: true
    permalink: /:collection/:path
  research:
    output: true
    permalink: /:collection/:path

# categories on the documentation site
docs_categories:
  - Strymon Core
  #- SnailTrail
  - Session Reconstruction
  - Further Information

research_categories:
  - Strymon
  - Components and use-cases

# DEFAULT VALUES
defaults:
  -
    scope:
      path: ""
      type: docs
    values:
      layout: "docs"
  -
    scope:
      path: ""
      type: research
    values:
      layout: "research"
  # we automatically apply the "SnailTrail" category to each file in the "_docs/snailtrail" subfolder
  -
    scope:
      path: "_docs/snailtrail"
      type: docs
    values:
      category: "SnailTrail"
  # similar for anything about sessionization
  -
    scope:
      path: "_docs/reconstruction"
      type: docs
    values:
      category: "Session Reconstruction"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Strymon
  avatar:
  favicon:
  gravatar: # Email MD5 hash
  description: "Strymon" # used by search engines

  # Header and footer text
  header_text: >
     <p><strong>Strymon</strong> is a platform for online modelling of enterprise datacenter behavior</p>

     <p><a class="button" href="/docs/getting-started">Get Started</a></p>
  header_text_feature_image:

  header_links:
    - title: Code
      url: /download
    - title: Documentation
      url: /docs
    - title: Research
      url: /research
    - title: Blog
      url: /blog

  footer_text: >
   Copyright © 2017 <a href="https://www.systems.ethz.ch/">ETH Zürich</a> | Theme based on <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>


  # Icons
  rss: false
  email_address:  # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "strymon-system"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "SystemsGroupETH"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page/:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - submodules
